# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o48VX49HiPU4VaAtKRpAGyr57u7y5oz-
"""

from IPython.display import display, HTML

html_code = """
<!DOCTYPE html>
<html>
<head>
    <title>My Portfolio</title>
    <style>
        body { font-family: Arial; text-align:center; background:#f4f4f4; }
        h1 { color: darkblue; }
        .card {
            background:white;
            width:400px;
            margin:auto;
            padding:20px;
            border-radius:10px;
            box-shadow:0 0 10px rgba(0,0,0,0.1);
        }
        input, textarea {
            width:90%;
            padding:8px;
            margin:5px;
        }
        button {
            padding:8px 15px;
            background:darkblue;
            color:white;
            border:none;
        }
    </style>
</head>
<body>

<div class="card">
<h1>Welcome to My Portfolio</h1>
<h2>Hello, I am Kalmesh Narendra</h2>

<h3>About Me</h3>
<p>I am a Python Developer Intern passionate about Web Development.</p>

<h3>Contact Me</h3>
<form>
<input type="text" placeholder="Your Name"><br>
<input type="email" placeholder="Your Email"><br>
<textarea placeholder="Your Message"></textarea><br>
<button>Send</button>
</form>
</div>

</body>
</html>
"""

display(HTML(html_code))